export const DIAS_PARA_HORAS = 24;

export const casesSeed = [
    {
        id: "C001",
        titulo: "Relíquia desaparecida no centro histórico",
        dificuldade: "FACIL",
        recompensa: 4500,
        xp: 80,
        tempoTotalHoras: 20 * DIAS_PARA_HORAS, // 20 dias
        localInicial: { pais: "Brasil", cidade: "Campinas" },
        resumo: "A joia roubada era a lendária Lágrima de Aeternum, uma relíquia antiga cravejada de ouro e um núcleo de cristal incandescente, conhecida por seu brilho quase sobrenatural.\n\nEla desapareceu do Museu do Centro Histórico, arrancada de um pedestal protegido por vidro reforçado durante a noite.\n\nAvaliada em cerca de R$ 25 milhões, seu valor real vai além do dinheiro, envolvendo séculos de história e segredos ainda não revelados. 🔎💎",
        imgItem: "/reliquiaDesaparecida.png",
        replayable: true,
        interrogatorios: [
            {
                id: "L001",
                local: "Floricultura",
                imgLocal: "/NPC/Floricultura.png",
                personagem: "Florista",
                imgPersonagem: "/NPC/Florista.png",
                cidade: "Campinas",
                pista: "A testemunha citou uma moeda usada em países vizinhos.",
            },
            {
                id: "L002",
                local: "Restaurante",
                imgLocal: "/NPC/Restaurante.png",
                personagem: "Garçom",
                imgPersonagem: "/NPC/Garcon.png",
                cidade: "Campinas",
                pista: "Teve um sujeito estranho aqui ontem à noite… não tirava os olhos de um livro antigo que trazia no bolso. Perguntou se eu sabia onde ficava a antiga rota dos navegadores portugueses… e pediu um prato típico de bacalhau.\nAntes de sair, comentou que precisava pegar um voo internacional ainda esta madrugada.",
            },
            {
                id: "L003",
                local: "Hospital",
                imgLocal: "/NPC/Hospital.png",
                personagem: "Médica",
                imgPersonagem: "/NPC/Medica.png",
                cidade: "Campinas",
                pista: "Havia palavras em português com sotaque diferente.",
            },
            {
                id: "L001_B",
                local: "Porto",
                imgLocal: "/Paises/Portugal.png",
                personagem: "Barqueiro",
                imgPersonagem: "/NPC/Barqueiro.png",
                cidade: "Lisboa",
                pista: "O sujeito que passou aqui tinha pressa. Perguntou sobre as rotas marítimas para o sul de Espanha, mencionou algo sobre Sevilha... E era um homem, com certeza.",
            },
            {
                id: "L001_C",
                local: "Floricultura",
                imgLocal: "/NPC/Floricultura.png",
                personagem: "Florista",
                imgPersonagem: "/NPC/Florista.png",
                cidade: "Lisboa",
                pista: "Vi um homem comprando flores, ele mencionou que estava indo para uma exposição no Triângulo das Artes em Madrid.",
            },
            {
                id: "L001_D",
                local: "Agente de Trânsito",
                imgLocal: "/NPC/Hospital.png",
                personagem: "Agente",
                imgPersonagem: "/NPC/AgenteTransito.png",
                cidade: "Lisboa",
                pista: "Multai um estrangeiro hoje mais cedo. Ele estava em um carro alugado perguntando o caminho para a fronteira com a Espanha, disse que não queria perder o festival de Flamenco. Era um cavalheiro bem vestido.",
            },
            {
                id: "L001_E",
                local: "Táxi",
                imgLocal: "/NPC/Taxi.png",
                personagem: "Taxista",
                imgPersonagem: "/NPC/Taxista.png",
                cidade: "Madrid",
                pista: "O passageiro que levei ontem não parava de reclamar do calor. Disse que sentia falta do 'Inverno de verdade' e das cúpulas coloridas do Kremlin em sua terra natal. Ah, e ele comentou que adora praticar esportes ao ar livre.",
            },
            {
                id: "L001_F",
                local: "Banco Central",
                imgLocal: "/NPC/Banco.png",
                personagem: "Banqueiro",
                imgPersonagem: "/NPC/Banqueiro.png",
                cidade: "Madrid",
                pista: "Um cavalheiro trocou uma grande quantia de Euros por Rublos hoje cedo. Ele mencionou que a política dos antigos Czares ainda influencia a cultura do seu próximo destino. Notei que ele carregava um equipamento de escalada, parece ser fã de esportes ao ar livre.",
            },
            {
                id: "L001_G",
                local: "Casa de Shows",
                imgLocal: "/NPC/Hospital.png",
                personagem: "Dançarina",
                imgPersonagem: "/NPC/Dancarina.png",
                cidade: "Madrid",
                pista: "Vi um homem bem vestido assistindo ao show. Ele comentou que o balé em sua cidade, perto da Praça Vermelha, era insuperável. Ele tinha um físico atlético, disse que pratica esportes ao ar livre sempre que pode.",
            },
            {
                id: "L001_H",
                local: "Restaurante",
                imgLocal: "/NPC/Restaurante.png",
                personagem: "Garçom",
                imgPersonagem: "/NPC/Garcon.png",
                cidade: "Moscou",
                pista: "Aquele sujeito me deu uma gorjeta generosa, mas parecia ansioso. Ele comentou que seu próximo destino era a cidade que nunca dorme, onde a Broadway brilha sob as luzes de neon. Ah, e ele vestia uma camisa de gola impecável, mencionou que pratica Polo sempre que pode.",
            },
            {
                id: "L001_I",
                local: "Porto",
                imgLocal: "/Paises/Portugal.png",
                personagem: "Barqueiro",
                imgPersonagem: "/NPC/Barqueiro.png",
                cidade: "Moscou",
                pista: "Vi um homem embarcando às pressas. Ele perguntou se havia balsas para atravessar o Atlântico até o porto de New Jersey, mas disse que seu destino final era o Central Park.",
            },
            {
                id: "L001_J",
                local: "Hospital",
                imgLocal: "/NPC/Hospital.png",
                personagem: "Médica",
                imgPersonagem: "/NPC/Medica.png",
                cidade: "Moscou",
                pista: "Atendi um homem que precisava de vacinas internacionais. Ele mencionou que estava indo para uma metrópole vibrante, famosa pela Estátua da Liberdade e pelo Empire State Building.",
            },
            {
                id: "L001_K",
                local: "Floricultura",
                imgLocal: "/NPC/Floricultura.png",
                personagem: "Florista",
                imgPersonagem: "/NPC/Barqueiro.png",
                cidade: "Nova York",
                pista: "Ah, sim! Um cavalheiro com sotaque estrangeiro comprou rosas brancas aqui agora mesmo. Ele parecia estar com pressa, mencionou que ia encontrar alguém em um restaurante próximo na Times Square.",
            },
            {
                id: "L001_L",
                local: "Restaurante",
                imgLocal: "/NPC/Restaurante.png",
                personagem: "Garçom",
                imgPersonagem: "/NPC/Garcon.png",
                cidade: "Nova York",
                pista: "Sinto muito, mas ele está sentado naquela mesa ali no fundo. Você veio prendê-lo?",
            },
            {
                id: "L001_M",
                local: "Táxi",
                imgLocal: "/NPC/Taxi.png",
                personagem: "Taxista",
                imgPersonagem: "/NPC/Taxista.png",
                cidade: "Nova York",
                pista: "Peguei um cara agora há pouco na 5ª Avenida. Ele estava bem nervoso, ficava olhando para trás o tempo todo. Deixei ele perto da Times Square.",
            },
        ],
    },
    {
        id: "C002",
        titulo: "Obra de Arte sumiu após o Leilão",
        dificuldade: "MEDIA",
        recompensa: 7500,
        xp: 150,
        tempoTotalHoras: 15 * DIAS_PARA_HORAS, // 15 dias
        localInicial: { pais: "França", cidade: "Paris" },
        resumo: "🖼️ Obra de Arte Sumiu após o Leilão\n📍 Local do crime: Paris, França 🇫🇷\n🕒 Horário estimado: 02:17 da manhã\n🏛️ Local: Hôtel des Ventes du Palais\n\nUma peça inestimável desapareceu misteriosamente logo após ser arrematada em um leilão de elite. O rastro leva a várias metrópoles globais. 🕵️‍♂️🎨",
        imgItem: "/ObradeArteLeilao.jpg",
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C003",
        titulo: "O Manuscrito que Nunca Existiu",
        dificuldade: "MEDIA",
        recompensa: 4000,
        xp: 150,
        tempoTotalHoras: 360, // 360 horas conforme pedido
        localInicial: { pais: "Áustria", cidade: "Viena" },
        resumo: "📜 O Manuscrito que Nunca Existiu\n📍 Local: Biblioteca Imperial de Viena, Áustria 🇦🇹\n\nUm documento que muitos acreditavam ser apenas uma lenda urbana foi roubado do cofre subterrâneo da Biblioteca Imperial. O manuscrito, supostamente escrito por um alquimista do século XVII, conteria segredos sobre a transmutação de metais e a vida eterna.\n\nA equipe Meridian foi acionada para recuperar esta peça inestimável antes que ela caia em mãos erradas. Sua missão começa em Viena. 🔎📚",
        imgItem: "/caso3_Manuscrito_que_nunca_existiu.png",
        replayable: true,
        interrogatorios: [],
    },
];

export const initialPlayer = {
    nome: "Recruta",
    nivel: 1,
    nivelTitulo: "Novato",
    classeEmoji: "🟢",
    classe: "Iniciante",
    xp: 0,
    dinheiro: 1000,
    especializacao: null,
    settings: {
        musicEnabled: true,
        clickSoundEnabled: true
    }

};