export const DIAS_PARA_HORAS = 24;

export const casesSeed = [
    {
        id: "C000",
        titulo: "O Roubo do Relógio Antigo",
        dificuldade: "FACIL",
        recompensa: 500,
        xp: 50,
        tempoTotalHoras: DIAS_PARA_HORAS * 365, // effectively unlimited
        localInicial: { pais: "Inglaterra", cidade: "Londres" },
        resumo: "CASO 0 (TUTORIAL) — O Roubo do Relógio Antigo\n📍 Local do Roubo: Museu Histórico em Londres, Inglaterra 🇬🇧\n\nEste é o seu primeiro caso na A.T.L.A.S. Siga as instruções do sistema para aprender a investigar, viajar e analisar as pistas no Laboratório para emitir um mandado de prisão.",
        imgItem: "/reliquiaDesaparecida.png",
        videoIntro: "/Videos/Caso0_Relogio_roubado.mp4",
        replayable: false,
        interrogatorios: [],
    },
    {
        id: "C001",
        titulo: "Relíquia desaparecida no centro histórico",
        dificuldade: "FACIL",
        recompensa: 2500,
        xp: 80,
        tempoTotalHoras: 20 * DIAS_PARA_HORAS, // 20 dias
        localInicial: { pais: "Brasil", cidade: "Campinas" },
        resumo: "A joia roubada era a lendária Lágrima de Aeternum, uma relíquia antiga cravejada de ouro e um núcleo de cristal incandescente, conhecida por seu brilho quase sobrenatural.\n\nEla desapareceu do Museu do Centro Histórico, arrancada de um pedestal protegido por vidro reforçado durante a noite.\n\nAvaliada em cerca de R$ 25 milhões, seu valor real vai além do dinheiro, envolvendo séculos de história e segredos ainda não revelados. 🔎💎",
        imgItem: "/reliquiaDesaparecida.png",
        replayable: true,
        procedural: true,
        interrogatorios: [
            {
                id: "L001",
                local: "Floricultura",
                imgLocal: "/NPC/Floricultura.png",
                personagem: "Florista",
                imgPersonagem: "/NPC/Florista.png",
                cidade: "Campinas",
                pista: "A testemunha citou uma moeda usada em países vizinhos.",
            },
            {
                id: "L002",
                local: "Restaurante",
                imgLocal: "/NPC/Restaurante.png",
                personagem: "Garçom",
                imgPersonagem: "/NPC/Garcon.png",
                cidade: "Campinas",
                pista: "Teve um sujeito estranho aqui ontem à noite… não tirava os olhos de um livro antigo que trazia no bolso. Perguntou se eu sabia onde ficava a antiga rota dos navegadores portugueses… e pediu um prato típico de bacalhau.\nAntes de sair, comentou que precisava pegar um voo internacional ainda esta madrugada.",
            },
            {
                id: "L003",
                local: "Hospital",
                imgLocal: "/NPC/Hospital.png",
                personagem: "Médica",
                imgPersonagem: "/NPC/Medica.png",
                cidade: "Campinas",
                pista: "Havia palavras em português com sotaque diferente.",
            },
            {
                id: "L001_B",
                local: "Porto",
                imgLocal: "/Paises/Portugal.png",
                personagem: "Barqueiro",
                imgPersonagem: "/NPC/Barqueiro.png",
                cidade: "Lisboa",
                pista: "O sujeito que passou aqui tinha pressa. Perguntou sobre as rotas marítimas para o sul de Espanha, mencionou algo sobre Sevilha... E era um homem, com certeza.",
            },
            {
                id: "L001_C",
                local: "Floricultura",
                imgLocal: "/NPC/Floricultura.png",
                personagem: "Florista",
                imgPersonagem: "/NPC/Florista.png",
                cidade: "Lisboa",
                pista: "Vi um homem comprando flores, ele mencionou que estava indo para uma exposição no Triângulo das Artes em Madrid.",
            },
            {
                id: "L001_D",
                local: "Agente de Trânsito",
                imgLocal: "/NPC/Hospital.png",
                personagem: "Agente",
                imgPersonagem: "/NPC/AgenteTransito.png",
                cidade: "Lisboa",
                pista: "Multai um estrangeiro hoje mais cedo. Ele estava em um carro alugado perguntando o caminho para a fronteira com a Espanha, disse que não queria perder o festival de Flamenco. Era um cavalheiro bem vestido.",
            },
            {
                id: "L001_E",
                local: "Táxi",
                imgLocal: "/NPC/Taxi.png",
                personagem: "Taxista",
                imgPersonagem: "/NPC/Taxista.png",
                cidade: "Madrid",
                pista: "O passageiro que levei ontem não parava de reclamar do calor. Disse que sentia falta do 'Inverno de verdade' e das cúpulas coloridas do Kremlin em sua terra natal. Ah, e ele comentou que adora praticar esportes ao ar livre.",
            },
            {
                id: "L001_F",
                local: "Banco Central",
                imgLocal: "/NPC/Banco.png",
                personagem: "Banqueiro",
                imgPersonagem: "/NPC/Banqueiro.png",
                cidade: "Madrid",
                pista: "Um cavalheiro trocou uma grande quantia de Euros por Rublos hoje cedo. Ele mencionou que a política dos antigos Czares ainda influencia a cultura do seu próximo destino. Notei que ele carregava um equipamento de escalada, parece ser fã de esportes ao ar livre.",
            },
            {
                id: "L001_G",
                local: "Casa de Shows",
                imgLocal: "/NPC/Hospital.png",
                personagem: "Dançarina",
                imgPersonagem: "/NPC/Dancarina.png",
                cidade: "Madrid",
                pista: "Vi um homem bem vestido assistindo ao show. Ele comentou que o balé em sua cidade, perto da Praça Vermelha, era insuperável. Ele tinha um físico atlético, disse que pratica esportes ao ar livre sempre que pode.",
            },
            {
                id: "L001_H",
                local: "Restaurante",
                imgLocal: "/NPC/Restaurante.png",
                personagem: "Garçom",
                imgPersonagem: "/NPC/Garcon.png",
                cidade: "Moscou",
                pista: "Aquele sujeito me deu uma gorjeta generosa, mas parecia ansioso. Ele comentou que seu próximo destino era a cidade que nunca dorme, onde a Broadway brilha sob as luzes de neon. Ah, e ele vestia uma camisa de gola impecável, mencionou que pratica Polo sempre que pode.",
            },
            {
                id: "L001_I",
                local: "Porto",
                imgLocal: "/Paises/Portugal.png",
                personagem: "Barqueiro",
                imgPersonagem: "/NPC/Barqueiro.png",
                cidade: "Moscou",
                pista: "Vi um homem embarcando às pressas. Ele perguntou se havia balsas para atravessar o Atlântico até o porto de New Jersey, mas disse que seu destino final era o Central Park.",
            },
            {
                id: "L001_J",
                local: "Hospital",
                imgLocal: "/NPC/Hospital.png",
                personagem: "Médica",
                imgPersonagem: "/NPC/Medica.png",
                cidade: "Moscou",
                pista: "Atendi um homem que precisava de vacinas internacionais. Ele mencionou que estava indo para uma metrópole vibrante, famosa pela Estátua da Liberdade e pelo Empire State Building.",
            },
            {
                id: "L001_K",
                local: "Floricultura",
                imgLocal: "/NPC/Floricultura.png",
                personagem: "Florista",
                imgPersonagem: "/NPC/Barqueiro.png",
                cidade: "Nova York",
                pista: "Ah, sim! Um cavalheiro com sotaque estrangeiro comprou rosas brancas aqui agora mesmo. Ele parecia estar com pressa, mencionou que ia encontrar alguém em um restaurante próximo na Times Square.",
            },
            {
                id: "L001_L",
                local: "Restaurante",
                imgLocal: "/NPC/Restaurante.png",
                personagem: "Garçom",
                imgPersonagem: "/NPC/Garcon.png",
                cidade: "Nova York",
                pista: "Sinto muito, mas ele está sentado naquela mesa ali no fundo. Você veio prendê-lo?",
            },
            {
                id: "L001_M",
                local: "Táxi",
                imgLocal: "/NPC/Taxi.png",
                personagem: "Taxista",
                imgPersonagem: "/NPC/Taxista.png",
                cidade: "Nova York",
                pista: "Peguei um cara agora há pouco na 5ª Avenida. Ele estava bem nervoso, ficava olhando para trás o tempo todo. Deixei ele perto da Times Square.",
            },
        ],
    },
    {
        id: "C002",
        titulo: "Obra de Arte sumiu após o Leilão",
        dificuldade: "MEDIA",
        recompensa: 4000,
        xp: 150,
        tempoTotalHoras: 15 * DIAS_PARA_HORAS, // 15 dias
        localInicial: { pais: "França", cidade: "Paris" },
        resumo: "🖼️ Obra de Arte Sumiu após o Leilão\n📍 Local do crime: Paris, França 🇫🇷\n🕒 Horário estimado: 02:17 da manhã\n🏛️ Local: Hôtel des Ventes du Palais\n\nUma peça inestimável desapareceu misteriosamente logo após ser arrematada em um leilão de elite. O rastro leva a várias metrópoles globais. 🕵️‍♂️🎨",
        imgItem: "/ObradeArteLeilao.jpg",
        replayable: true,
        procedural: true,
        interrogatorios: [],
    },
    {
        id: "C003",
        titulo: "O Manuscrito que Nunca Existiu",
        dificuldade: "MEDIA",
        recompensa: 4000,
        xp: 150,
        tempoTotalHoras: 360, // 360 horas conforme pedido
        localInicial: { pais: "Áustria", cidade: "Viena" },
        resumo: "📜 O Manuscrito que Nunca Existiu\n📍 Local: Biblioteca Imperial de Viena, Áustria 🇦🇹\n\nUm documento que muitos acreditavam ser apenas uma lenda urbana foi roubado do cofre subterrâneo da Biblioteca Imperial. O manuscrito, supostamente escrito por um alquimista do século XVII, conteria segredos sobre a transmutação de metais e a vida eterna.\n\nA equipe Meridian foi acionada para recuperar esta peça inestimável antes que ela caia em mãos erradas. Sua missão começa em Viena. 🔎📚",
        imgItem: "/caso3_Manuscrito_que_nunca_existiu.png",
        replayable: true,
        procedural: true,
        interrogatorios: [],
    },
    {
        id: "C004",
        titulo: "O Diamante que Muda de Cor",
        dificuldade: "FACIL",
        recompensa: 2500,
        xp: 80,
        tempoTotalHoras: 480,
        localInicial: { pais: "África do Sul", cidade: "Cidade do Cabo" },
        resumo: "💎 CASO 4 — O Diamante que Muda de Cor\n📍 Local: Museu de Ciências da Cidade do Cabo, África do Sul 🇿🇦\n\nUm diamante único, conhecido por mudar de cor sob diferentes condições de luz, foi roubado do Museu de Ciências. O ladrão foi visto fugindo logo após o crime.\n\nSua missão é rastrear o criminoso através de várias capitais globais e recuperar a joia. 🔎💎",
        imgItem: "/reliquiaDesaparecida.png",
        replayable: true,
        procedural: true,
        interrogatorios: [],
    },
    {
        id: "C005",
        titulo: "O Mapa que Não Aparece em Nenhum Atlas",
        recompensa: 4500,
        xp: 180,
        tempoTotalHoras: 360,
        dificuldade: "MEDIO",
        resumo: "🗺️ O Mapa que Não Aparece em Nenhum Atlas\n📍 Local: Arquivo Nacional de Lisboa, Portugal 🇵🇹\n\nUm pesquisador misterioso solicitou acesso a um documento cartográfico raro e confidencial. Minutos depois, o mapa desapareceu sem deixar vestígios. Ninguém sabe como ele saiu do edifício fortemente vigiado.\n\nSua missão é rastrear o paradeiro do mapa antes que ele seja vendido no mercado negro. 🔎🗺️",
        localInicial: { pais: "Portugal", cidade: "Lisboa" },
        procedural: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C006",
        titulo: "O Leilão Fantasma",
        recompensa: 4000,
        xp: 200,
        tempoTotalHoras: 360,
        dificuldade: "MEDIO",
        resumo: "🏛️ O Leilão Fantasma\n📍 Local: Casa de Leilões Imperial, Viena, Áustria 🇦🇹\n\nUma peça inestimável desapareceu misteriosamente logo após ser arrematada em um leilão de elite. O comprador nunca apareceu para retirar o item, e as câmeras foram desligadas exatamente na hora errada.\n\nSua missão é descobrir quem orquestrou o desaparecimento e recuperar a peça. 🔎🏛️",
        localInicial: { pais: "Áustria", cidade: "Viena" },
        procedural: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C007",
        titulo: "O Contêiner que Chegou Vazio",
        recompensa: 5500,
        xp: 220,
        tempoTotalHoras: 360,
        dificuldade: "MEDIO",
        resumo: "📦 O Contêiner que Chegou Vazio\n📍 Local: Porto de Lisboa, Portugal 🇵🇹\n\nUm contêiner chegou ao porto totalmente vazio. A carga valiosa desapareceu sem deixar rastros durante o trajeto marítimo. Os lacres estavam intactos e a documentação perfeita.\n\nSua missão é descobrir em que ponto a carga foi desviada e identificar o responsável. 🔎📦",
        localInicial: { pais: "Portugal", cidade: "Lisboa" },
        procedural: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C008",
        titulo: "O Código que Não Existe",
        recompensa: 4000,
        xp: 250,
        tempoTotalHoras: 360,
        dificuldade: "MEDIO",
        resumo: "💻 O Código que Não Existe\n📍 Local: Centro de Dados de Seul, Coreia do Sul 🇰🇷\n\nUm código misterioso surgiu em servidores críticos de Seul e desapareceu sem deixar rastros minutos depois. Nenhum login foi registrado, mas dados confidenciais foram acessados.\n\nAlguém está por trás dessa operação fantasma. Sua missão é rastrear a origem do acesso e identificar o invasor. 🔎💻",
        localInicial: { pais: "Coreia do Sul", cidade: "Seul" },
        procedural: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C009",
        titulo: "Protocolo Fantasma (MODO DIFÍCIL)",
        dificuldade: "DIFICIL",
        recompensa: 10000,
        xp: 500,
        tempoTotalHoras: 999, // Sem prazo fixo no UI, mas mantemos valor positivo por segurança de sistema 
        localInicial: { pais: "Alemanha", cidade: "Berlim" },
        resumo: "⚠️ PROTOCOLO FANTASMA ATIVADO\n\nUm artefato de segurança máxima da A.T.L.A.S. foi fragmentado e espalhado por diversos nós do submundo digital. Vários agentes foram detectados tentando a mesma recuperação.\n\nApenas o mais rápido e eficiente garantirá a reconfiguração do sistema. Prepare-se: você está competindo em tempo real contra outros agentes de elite.\n\nRegras de Engajamento:\n1. Sem Fundo de Reserva ($ 0,00 iniciais).\n2. 10 Etapas Críticas.\n3. Vitória única para o primeiro a capturar o sinal. 🕵️‍♂️⚡",
        imgItem: "/reliquiaDesaparecida.png",
        isCompetitive: true,
        maxPlayers: 10,
        minPlayers: 2,
        waitTimeout: 180,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C010",
        titulo: "O Cofre que Nunca Foi Aberto",
        dificuldade: "DIFICIL",
        recompensa: 10000,
        xp: 500,
        tempoTotalHoras: 999, // Sem prazo fixo no UI, apenas competitivo
        localInicial: { pais: "Reino Unido", cidade: "Londres" },
        resumo: "🪙 O COFRE QUE NUNCA FOI ABERTO\n\nUm cofre ultra seguro, localizado em uma instituição financeira internacional… foi violado. Não há sinais de arrombamento. Nenhum sistema acusou acesso. Nenhuma chave foi usada.\n\nDentro dele havia documentos classificados, registros financeiros secretos e identidades protegidas. A A.T.L.A.S suspeita que isso não foi um roubo comum…\n\nA Agência convoca todos Agentes Disponíveis.\n\nRegras de Engajamento:\n1. Sem Fundo de Reserva ($ 0,00 iniciais).\n2. 10 Etapas Críticas.\n3. Vitória única para o primeiro a recuperar os documentos. 🕵️‍♂️⚡",
        imgItem: "/reliquiaDesaparecida.png", // Imagem padrão
        isCompetitive: true,
        maxPlayers: 10,
        minPlayers: 2,
        waitTimeout: 180,
        replayable: true,
        interrogatorios: [],
    },

    // ============ CASOS PROCEDURAIS (C011+) ============
    {
        id: "C011",
        titulo: "O Relicário Desaparecido",
        dificuldade: "FACIL",
        recompensa: 900,
        xp: 120,
        tempoTotalHoras: 360,
        localInicial: { pais: "Portugal", cidade: "Lisboa" },
        resumo: "Um pequeno relicário histórico desapareceu de uma coleção privada em Lisboa sem qualquer sinal de invasão. Os responsáveis pelo local afirmam que tudo parecia normal até perceberem o sumiço horas depois. O objeto possui valor cultural significativo e pode ser facilmente revendido no mercado clandestino. Sua missão é identificar o responsável antes que o item desapareça definitivamente.",
        procedural: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C012",
        titulo: "Entrega Fantasma",
        dificuldade: "FACIL",
        recompensa: 1000,
        xp: 130,
        tempoTotalHoras: 360,
        localInicial: { pais: "Espanha", cidade: "Barcelona" },
        resumo: "Uma encomenda valiosa foi registrada como entregue, mas nunca chegou ao destinatário em Barcelona. O sistema logístico não apresenta falhas aparentes, e todos os registros indicam uma entrega concluída. Há indícios de manipulação durante o trajeto. Você deve rastrear o responsável antes que a trilha desapareça.",
        procedural: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C013",
        titulo: "Código Quebrado",
        dificuldade: "MEDIO",
        recompensa: 1800,
        xp: 180,
        tempoTotalHoras: 240,
        localInicial: { pais: "Alemanha", cidade: "Berlim" },
        resumo: "Um terminal financeiro apresentou movimentações suspeitas envolvendo criptomoedas sem origem definida. Nenhuma conta oficial foi comprometida, mas valores foram transferidos de forma silenciosa. Especialistas indicam que alguém manipulou o sistema internamente. Você precisa seguir os rastros digitais e descobrir quem executou essa operação.",
        procedural: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C014",
        titulo: "A Porta Que Nunca Abriu",
        dificuldade: "MEDIO",
        recompensa: 2000,
        xp: 200,
        tempoTotalHoras: 240,
        localInicial: { pais: "Brasil", cidade: "São Paulo" },
        resumo: "Uma sala restrita em um prédio corporativo foi acessada sem qualquer registro de entrada. Nenhuma fechadura foi violada e os sistemas não indicam falhas. Mesmo assim, documentos desapareceram. Há sinais de acesso altamente especializado. Você deve investigar como isso foi possível e encontrar o responsável.",
        procedural: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C015",
        titulo: "Leilão Silencioso",
        dificuldade: "DIFICIL",
        recompensa: 9000,
        xp: 300,
        tempoTotalHoras: 999,
        localInicial: { pais: "Itália", cidade: "Roma" },
        resumo: "Durante um leilão privado em Roma, uma obra de valor incalculável foi substituída por uma réplica perfeita sem que ninguém percebesse. Especialistas confirmaram a troca apenas horas depois, quando o responsável já havia desaparecido. Você foi convocado junto com outros agentes da A.T.L.A.S. para investigar o caso, mas apenas um chegará primeiro à verdade. O tempo é curto, e essa é uma corrida contra o tempo para recuperar a peça antes que desapareça.",
        procedural: true,
        isCompetitive: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C016",
        titulo: "Rastro Invisível",
        dificuldade: "DIFICIL",
        recompensa: 10000,
        xp: 320,
        tempoTotalHoras: 999,
        localInicial: { pais: "Suíça", cidade: "Zurich" },
        resumo: "Uma série de transferências internacionais ocorreu sem qualquer registro oficial de origem ou destino. Nenhum sistema acusa erro, mas valores desapareceram em sequência. Os indícios apontam para uma operação altamente sofisticada. Você foi convocado junto com outros agentes da A.T.L.A.S. e precisa agir rápido. Esta é uma corrida contra o tempo para rastrear o responsável antes que o dinheiro desapareça completamente.",
        procedural: true,
        isCompetitive: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C017",
        titulo: "Sombras no Porto",
        dificuldade: "DIFICIL",
        recompensa: 8500,
        xp: 340,
        tempoTotalHoras: 999,
        localInicial: { pais: "Países Baixos", cidade: "Roterdã" },
        resumo: "Movimentações irregulares foram detectadas em cargas que passaram por um porto internacional, sem registro de inspeção. Parte da mercadoria desapareceu e ninguém assumiu responsabilidade. Há indícios de manipulação logística avançada. Você foi convocado junto com outros agentes da A.T.L.A.S., e apenas um resolverá o caso primeiro. É uma corrida contra o tempo para impedir que a operação continue.",
        procedural: true,
        isCompetitive: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C018",
        titulo: "Rede Fragmentada",
        dificuldade: "LENDARIO",
        recompensa: 13000,
        xp: 500,
        tempoTotalHoras: 999,
        localInicial: { pais: "Estados Unidos", cidade: "Nova York" },
        resumo: "Diversas falhas aparentemente isoladas começaram a surgir em sistemas de diferentes países, todas com padrões semelhantes. Nenhum ataque direto foi identificado, mas os dados indicam uma coordenação invisível. Você foi convocado junto com outros agentes da A.T.L.A.S., em uma corrida contra o tempo para entender e interromper essa rede antes que cause impactos globais irreversíveis.",
        procedural: true,
        isCompetitive: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C019",
        titulo: "Operação Espelho Negro",
        dificuldade: "LENDARIO",
        recompensa: 14000,
        xp: 550,
        tempoTotalHoras: 999,
        localInicial: { pais: "Reino Unido", cidade: "Londres" },
        resumo: "Identidades falsas começaram a surgir simultaneamente em múltiplos sistemas governamentais, todas perfeitamente válidas e impossíveis de rastrear. Nenhuma falha foi encontrada, mas os dados indicam uma manipulação coordenada em larga escala. Você foi convocado junto com outros agentes da A.T.L.A.S., em uma corrida contra o tempo para impedir que essa rede de identidades comprometa estruturas críticas.",
        procedural: true,
        isCompetitive: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C020",
        titulo: "A Sombra Meridian",
        dificuldade: "LENDARIO",
        recompensa: 14000,
        xp: 600,
        tempoTotalHoras: 999,
        localInicial: { pais: "Suíça", cidade: "Genebra" },
        resumo: "Movimentações discretas da organização Meridian começaram a aparecer em diferentes regiões do mundo ao mesmo tempo. Nenhum evento isolado chama atenção, mas juntos formam um padrão claro de operação coordenada. Você foi convocado junto com outros agentes da A.T.L.A.S., em uma corrida contra o tempo para identificar e impedir esse plano antes que ele se concretize. Se falhar, as consequências podem ultrapassar fronteiras e causar impactos globais.",
        procedural: true,
        isCompetitive: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C021",
        titulo: "O Pacote Extraviado",
        dificuldade: "FACIL",
        xp: 120,
        recompensa: 900,
        tempoTotalHoras: 360,
        localInicial: { pais: "Espanha", cidade: "Madrid" },
        resumo: "Um pacote de pequeno porte desapareceu durante uma entrega urbana em Madrid sem qualquer registro de falha no sistema. O destinatário afirma que aguardava a encomenda, mas ela nunca chegou ao local indicado. O conteúdo não é oficialmente valioso, mas pode conter algo importante. Sua missão é descobrir quem desviou o pacote antes que ele desapareça completamente.",
        procedural: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C022",
        titulo: "Registro Duplicado",
        dificuldade: "FACIL",
        xp: 130,
        recompensa: 1000,
        tempoTotalHoras: 360,
        localInicial: { pais: "Áustria", cidade: "Viena" },
        resumo: "Um documento oficial apareceu duplicado em um sistema administrativo em Viena, com pequenas diferenças quase imperceptíveis. Nenhum funcionário assumiu a criação do segundo registro, e ambos parecem autênticos. Há suspeita de manipulação discreta de dados. Você deve investigar a origem da duplicação antes que outros registros sejam comprometidos.",
        procedural: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C023",
        titulo: "A Chave Errada",
        dificuldade: "FACIL",
        xp: 140,
        recompensa: 1000,
        tempoTotalHoras: 360,
        localInicial: { pais: "Alemanha", cidade: "Munique" },
        resumo: "Uma sala restrita foi aberta utilizando uma credencial válida, mas o usuário associado nega qualquer envolvimento. Nenhum dano foi causado, porém um item desapareceu do interior. Os registros indicam acesso legítimo, mas algo não está certo. Sua missão é descobrir quem utilizou essa identidade indevidamente.",
        procedural: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C024",
        titulo: "Linha Cruzada",
        dificuldade: "MEDIO",
        xp: 180,
        recompensa: 1800,
        tempoTotalHoras: 240,
        localInicial: { pais: "Países Baixos", cidade: "Amsterdã" },
        resumo: "Uma comunicação interna foi interceptada em um sistema corporativo em Amsterdã, contendo informações que não deveriam circular entre departamentos. Nenhuma invasão foi detectada, e os acessos parecem legítimos. Há indícios de alguém manipulando permissões de forma silenciosa. Você deve identificar a origem dessa falha antes que informações mais críticas vazem.",
        procedural: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C025",
        titulo: "Carga Desviada",
        dificuldade: "MEDIO",
        xp: 200,
        recompensa: 2000,
        tempoTotalHoras: 240,
        localInicial: { pais: "Argentina", cidade: "Buenos Aires" },
        resumo: "Uma remessa internacional teve parte de sua carga desviada durante uma parada logística em Buenos Aires. Nenhum registro aponta irregularidade, mas o peso final não confere com o inicial. A operação foi executada com precisão e sem chamar atenção. Você deve rastrear o ponto de desvio e identificar o responsável.",
        procedural: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C026",
        titulo: "Identidade Temporária",
        dificuldade: "MEDIO",
        xp: 220,
        recompensa: 2000,
        tempoTotalHoras: 240,
        localInicial: { pais: "Canadá", cidade: "Toronto" },
        resumo: "Uma identidade temporária foi utilizada para acessar sistemas internos em Toronto, mas desapareceu logo após o uso. Nenhum registro de criação foi encontrado, e o acesso foi feito com credenciais válidas. Há indícios de uma brecha explorada de forma inteligente. Você precisa descobrir quem criou essa identidade antes que o método seja reutilizado.",
        procedural: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C027",
        titulo: "O Cofre Secundário",
        dificuldade: "DIFICIL",
        xp: 300,
        recompensa: 9000,
        tempoTotalHoras: 999,
        localInicial: { pais: "Suíça", cidade: "Zurich" },
        resumo: "Um cofre secundário em uma instituição financeira em Zurich foi acessado sem qualquer registro de abertura oficial. O conteúdo desapareceu sem deixar rastros, e nenhum sistema acusa violação. Os indícios apontam para uma operation extremamente precisa e planejada. Você foi convocado junto com outros agentes da A.T.L.A.S. para investigar o caso, mas apenas um chegará primeiro à verdade. Esta é uma corrida contra o tempo para recuperar o que foi levado.",
        procedural: true,
        isCompetitive: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C028",
        titulo: "Rota Paralela",
        dificuldade: "DIFICIL",
        xp: 320,
        recompensa: 10000,
        tempoTotalHoras: 999,
        localInicial: { pais: "Singapura", cidade: "Singapura" },
        resumo: "Uma rota logística paralela foi identificada operando sem autorização em rotas oficiais no sudeste asiático. Nenhuma documentação reconhece sua existência, mas cargas foram movimentadas com sucesso por ela. O esquema indica planejamento avançado e execução discreta. Você foi convocado junto com outros agentes da A.T.L.A.S. e precisa agir rapidamente. É uma corrida contra o tempo para interromper essa operação clandestina.",
        procedural: true,
        isCompetitive: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C029",
        titulo: "Substituição Perfeita",
        dificuldade: "DIFICIL",
        xp: 340,
        recompensa: 9500,
        tempoTotalHoras: 999,
        localInicial: { pais: "Áustria", cidade: "Viena" },
        resumo: "Um item de alto valor foi substituído por uma réplica perfeita em uma galeria em Viena, sem que nenhum sensor fosse ativado. Especialistas só perceberam a troca após análise detalhada. O responsável demonstrou alto nível técnico e conhecimento do ambiente. Você foi convocado junto com outros agentes da A.T.L.A.S., e apenas um resolverá o caso primeiro. É uma corrida contra o tempo para encontrar o original.",
        procedural: true,
        isCompetitive: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C030",
        titulo: "Operação Invisível",
        dificuldade: "DIFICIL",
        xp: 360,
        recompensa: 10000,
        tempoTotalHoras: 999,
        localInicial: { pais: "China", cidade: "Xangai" },
        resumo: "Uma série de pequenas operações ocorreu em diferentes pontos de uma cidade portuária em Xangai, todas aparentemente desconectadas. No entanto, juntas formam um padrão claro de movimentação estratégica. Nenhum suspeito foi identificado até agora. Você foi convocado junto com outros agentes da A.T.L.A.S., em uma corrida contra o tempo para conectar os eventos e impedir que a operação avance.",
        procedural: true,
        isCompetitive: true,
        replayable: true,
        interrogatorios: [],
    },
    {
        id: "C031",
        titulo: "Bilhete Sem Destino",
        dificuldade: "FACIL",
        xp: 140,
        valorAdiantamento: 350,
        recompensa: 950,
        tempoTotalHoras: 480,
        resumo: "Um envelope lacrado desapareceu minutos antes de ser entregue em Dublin. Nenhum sinal de arrombamento foi encontrado e poucos sabiam de sua existência. O conteúdo pode parecer simples, mas alguém claramente sabia o que procurar. Sua missão é descobrir quem interceptou o bilhete antes que ele desapareça para sempre.",
        localInicial: { pais: "Irlanda", cidade: "Dublin" },
        procedural: true
    },
    {
        id: "C032",
        titulo: "Janela Aberta",
        dificuldade: "FACIL",
        xp: 150,
        valorAdiantamento: 400,
        recompensa: 1000,
        tempoTotalHoras: 480,
        resumo: "Uma sala segura foi encontrada vazia em Praga, com apenas uma janela entreaberta e nenhum registro de entrada. Nada parece quebrado, mas um objeto importante sumiu discretamente. Alguém entrou e saiu sem deixar marcas. Você deve reconstruir os passos do invasor e encontrar o item perdido.",
        localInicial: { pais: "República Tcheca", cidade: "Praga" },
        procedural: true
    },
    {
        id: "C033",
        titulo: "Documento Reescrito",
        dificuldade: "FACIL",
        xp: 155,
        valorAdiantamento: 420,
        recompensa: 1000,
        tempoTotalHoras: 480,
        resumo: "Um contrato oficial armazenado em Budapeste reapareceu com cláusulas alteradas, sem qualquer sinal de edição registrada. Os responsáveis juram que o arquivo estava protegido. Alguém mexeu onde ninguém deveria tocar. Sua missão é identificar quem manipulou o documento antes que ele produza efeitos reais.",
        localInicial: { pais: "Hungria", cidade: "Budapeste" },
        procedural: true
    },
    {
        id: "C034",
        titulo: "Eco no Corredor",
        dificuldade: "FACIL",
        xp: 160,
        valorAdiantamento: 450,
        recompensa: 1000,
        tempoTotalHoras: 480,
        resumo: "Funcionários em Atenas relataram movimentação em um corredor restrito durante a madrugada, mas nenhuma câmera registrou presença. Pela manhã, um pequeno item desapareceu do setor. O responsável agiu com calma e precisão. Você deve seguir as pistas e descobrir quem passou por ali.",
        localInicial: { pais: "Grécia", cidade: "Atenas" },
        procedural: true
    },
    {
        id: "C035",
        titulo: "Etiqueta Trocada",
        dificuldade: "FACIL",
        xp: 165,
        valorAdiantamento: 500,
        recompensa: 1000,
        tempoTotalHoras: 480,
        resumo: "Uma peça comum em exposição em Bruxelas recebeu uma etiqueta errada e, horas depois, desapareceu discretamente. O erro parecia pequeno demais para chamar atenção, mas foi calculado. Alguém usou a distração perfeita. Sua missão é descobrir quem planejou a troca e recuperar o objeto.",
        localInicial: { pais: "Bélgica", cidade: "Bruxelas" },
        procedural: true
    },
    {
        id: "C036",
        titulo: "Senha Temporária",
        dificuldade: "MEDIO",
        xp: 210,
        valorAdiantamento: 750,
        recompensa: 1900,
        tempoTotalHoras: 360,
        resumo: "Uma senha temporária foi criada e utilizada em Oslo para acessar dados internos sigilosos. Poucos minutos depois, o acesso desapareceu como se nunca tivesse existido. Nenhum funcionário reconhece a autorização. Você deve descobrir quem criou essa brecha e impedir novo uso do método.",
        localInicial: { pais: "Noruega", cidade: "Oslo" },
        procedural: true
    },
    {
        id: "C037",
        titulo: "Carga Incompleta",
        dificuldade: "MEDIO",
        xp: 220,
        valorAdiantamento: 800,
        recompensa: 2000,
        tempoTotalHoras: 360,
        resumo: "Uma remessa internacional chegou a Vancouver com peso correto, mas parte do conteúdo foi substituído por material sem valor. Os lacres pareciam intactos e a documentação está perfeita. A troca foi feita por alguém experiente. Você precisa descobrir em que ponto ocorreu o desvio.",
        localInicial: { pais: "Canadá", cidade: "Vancouver" },
        procedural: true
    },
    {
        id: "C038",
        titulo: "Mapa Rasurado",
        dificuldade: "MEDIO",
        xp: 230,
        valorAdiantamento: 850,
        recompensa: 2000,
        tempoTotalHoras: 360,
        resumo: "Um mapa histórico em Lima apareceu com marcações recentes indicando locais estratégicos. O documento estava protegido e ninguém deveria ter acesso a ele. As anotações parecem parte de algo maior em preparação. Você deve seguir as novas marcas e identificar quem as deixou.",
        localInicial: { pais: "Peru", cidade: "Lima" },
        procedural: true
    },
    {
        id: "C039",
        titulo: "Rota Interrompida",
        dificuldade: "MEDIO",
        xp: 240,
        valorAdiantamento: 900,
        recompensa: 2000,
        tempoTotalHoras: 360,
        resumo: "Uma rota regular de transporte foi alterada silenciosamente em Casablanca por poucas horas, tempo suficiente para algo desaparecer no trajeto. Depois disso, tudo voltou ao normal. Nenhum superior autorizou a mudança. Você deve rastrear quem manipulou o percurso e por quê.",
        localInicial: { pais: "Marrocos", cidade: "Casablanca" },
        procedural: true
    },
    {
        id: "C040",
        titulo: "A Voz Errada",
        dificuldade: "MEDIO",
        xp: 250,
        valorAdiantamento: 950,
        recompensa: 2000,
        tempoTotalHoras: 360,
        resumo: "Uma ordem importante foi transmitida por voz em Auckland e seguida por toda a equipe, mas depois descobriram que o superior jamais deu tal comando. Ninguém sabe como a falsificação convenceu tantas pessoas. O autor conhece rotinas internas e agiu com precisão. Sua missão é encontrar o impostor antes que volte a agir.",
        localInicial: { pais: "Nova Zelândia", cidade: "Auckland" },
        procedural: true
    },
    {
        id: "C041",
        titulo: "Arquivo Ausente",
        dificuldade: "FACIL",
        xp: 170,
        valorAdiantamento: 750,
        recompensa: 950,
        tempoTotalHoras: 480,
        resumo: "Um arquivo físico desapareceu de um setor administrativo em Oslo sem qualquer registro de retirada. Nenhuma porta foi forçada e poucos sabiam da existência do documento. O conteúdo pode revelar informações importantes. Sua missão é encontrar quem levou o material antes que ele seja destruído.",
        localInicial: { pais: "Noruega", cidade: "Oslo" },
        procedural: true
    },
    {
        id: "C042",
        titulo: "Pacote Sem Assinatura",
        dificuldade: "FACIL",
        xp: 175,
        valorAdiantamento: 760,
        recompensa: 980,
        tempoTotalHoras: 480,
        resumo: "Uma encomenda registrada como entregue em Genebra não possui assinatura válida nem confirmação visual. O destinatário afirma nunca ter recebido nada. Os registros existem, mas a entrega não. Você deve rastrear quem desviou o pacote antes que a pista desapareça.",
        localInicial: { pais: "Suíça", cidade: "Genebra" },
        procedural: true
    },
    {
        id: "C043",
        titulo: "Etiqueta Errada",
        dificuldade: "FACIL",
        xp: 180,
        valorAdiantamento: 780,
        recompensa: 1000,
        tempoTotalHoras: 480,
        resumo: "Uma peça comum recebeu identificação trocada em um depósito em Bruxelas e desapareceu horas depois. O erro parecia pequeno demais para chamar atenção, mas claramente foi planejado. Alguém manipulou os registros para esconder o sumiço. Descubra quem está por trás da troca.",
        localInicial: { pais: "Bélgica", cidade: "Bruxelas" },
        procedural: true
    },
    {
        id: "C044",
        titulo: "Porta Entreaberta",
        dificuldade: "FACIL",
        xp: 185,
        valorAdiantamento: 800,
        recompensa: 1000,
        tempoTotalHoras: 480,
        resumo: "Uma sala reservada em Lisboa foi encontrada aberta pela manhã, embora ninguém tenha relatado uso noturno. Nada parecia fora do lugar até perceberem a falta de um item discreto. O invasor agiu com calma e precisão. Sua missão é seguir os rastros deixados para trás.",
        localInicial: { pais: "Portugal", cidade: "Lisboa" },
        procedural: true
    },
    {
        id: "C045",
        titulo: "Mensagem Rasgada",
        dificuldade: "FACIL",
        xp: 190,
        valorAdiantamento: 820,
        recompensa: 1000,
        tempoTotalHoras: 480,
        resumo: "Uma mensagem importante foi destruída parcialmente antes de chegar ao destinatário em Dublin. O pouco que restou sugere que alguém queria atrasar uma decisão urgente. O responsável ainda pode estar próximo. Descubra quem interceptou a comunicação.",
        localInicial: { pais: "Irlanda", cidade: "Dublin" },
        procedural: true
    },
    {
        id: "C046",
        titulo: "Linha Oculta",
        dificuldade: "MEDIO",
        xp: 220,
        valorAdiantamento: 900,
        recompensa: 1800,
        tempoTotalHoras: 384,
        resumo: "Uma linha de acesso secundária foi utilizada em Berlim para consultar dados internos sem autorização. O uso durou poucos minutos e desapareceu dos registros principais. Alguém conhece bem a estrutura do sistema. Você deve encontrar o responsável antes que ele volte a agir.",
        localInicial: { pais: "Alemanha", cidade: "Berlim" },
        procedural: true
    },
    {
        id: "C047",
        titulo: "Carga Silenciosa",
        dificuldade: "MEDIO",
        xp: 230,
        valorAdiantamento: 950,
        recompensa: 1900,
        tempoTotalHoras: 384,
        resumo: "Uma carga internacional passou por Barcelona com lacres intactos, mas parte do conteúdo foi substituída por material sem valor. A documentação parece perfeita e ninguém percebeu o desvio. A operação foi feita por mãos experientes. Você deve descobrir onde a troca ocorreu.",
        localInicial: { pais: "Espanha", cidade: "Barcelona" },
        procedural: true
    },
    {
        id: "C048",
        titulo: "Crachá Temporário",
        dificuldade: "MEDIO",
        xp: 235,
        valorAdiantamento: 980,
        recompensa: 2000,
        tempoTotalHoras: 384,
        resumo: "Um crachá temporário surgiu em um prédio corporativo em Toronto e foi usado para acessar áreas restritas. Horas depois, deixou de existir nos registros. Nenhum funcionário reconhece sua emissão. Você precisa identificar quem criou essa credencial fantasma.",
        localInicial: { pais: "Canadá", cidade: "Toronto" },
        procedural: true
    },
    {
        id: "C049",
        titulo: "Rota Espelhada",
        dificuldade: "MEDIO",
        xp: 240,
        valorAdiantamento: 1000,
        recompensa: 2000,
        tempoTotalHoras: 384,
        resumo: "Uma rota de transporte foi duplicada digitalmente em Roterdã, fazendo duas cargas parecerem uma só. O erro permitiu que mercadorias desaparecessem sem chamar atenção. O esquema demonstra planejamento preciso. Você deve desmontar a fraude e rastrear os envolvidos.",
        localInicial: { pais: "Países Baixos", cidade: "Roterdã" },
        procedural: true
    },
    {
        id: "C050",
        titulo: "Comando Falso",
        dificuldade: "MEDIO",
        xp: 250,
        valorAdiantamento: 1050,
        recompensa: 2000,
        tempoTotalHoras: 384,
        resumo: "Uma ordem operacional falsa foi aceita como legítima em Viena e seguida por toda uma equipe. Quando perceberam o erro, já era tarde demais. O autor conhece rotinas internas e protocolos de confiança. Sua missão é descobrir quem imitou a autoridade real.",
        localInicial: { pais: "Áustria", cidade: "Viena" },
        procedural: true
    },
    {
        id: "C051",
        titulo: "Envelope de Vidro",
        dificuldade: "FACIL",
        xp: 195,
        valorAdiantamento: 830,
        recompensa: 1000,
        tempoTotalHoras: 480,
        resumo: "Um envelope selado desapareceu de uma recepção em Genebra enquanto dezenas de pessoas circulavam pelo local. Nenhuma câmera mostrou claramente o momento do sumiço. O conteúdo pode comprometer acordos importantes. Descubra quem o levou.",
        localInicial: { pais: "Suíça", cidade: "Genebra" },
        procedural: true
    },
    {
        id: "C052",
        titulo: "Objeto Trocado",
        dificuldade: "FACIL",
        xp: 200,
        valorAdiantamento: 850,
        recompensa: 1000,
        tempoTotalHoras: 480,
        resumo: "Uma peça decorativa comum em Paris foi substituída por uma réplica barata. O valor real estava escondido em sua história, não em sua aparência. Quem agiu sabia exatamente o que procurar. Você deve recuperar o original.",
        localInicial: { pais: "França", cidade: "Paris" },
        procedural: true
    },
    {
        id: "C053",
        titulo: "Senha Curta",
        dificuldade: "MEDIO",
        xp: 255,
        valorAdiantamento: 1100,
        recompensa: 2000,
        tempoTotalHoras: 384,
        resumo: "Uma senha temporária foi usada em Londres para autorizar movimentações que ninguém aprovou. O acesso durou pouco e sumiu dos logs principais. O responsável entende bem como apagar rastros. Você deve agir rápido para encontrá-lo.",
        localInicial: { pais: "Reino Unido", cidade: "Londres" },
        procedural: true
    },
    {
        id: "C054",
        titulo: "Mapa Invertido",
        dificuldade: "MEDIO",
        xp: 260,
        valorAdiantamento: 1150,
        recompensa: 2000,
        tempoTotalHoras: 384,
        resumo: "Um mapa técnico em Praga foi alterado discretamente, invertendo rotas e posições estratégicas. O erro só foi notado quando operações começaram a falhar. Não foi acidente. Você precisa descobrir quem sabotou as informações.",
        localInicial: { pais: "República Tcheca", cidade: "Praga" },
        procedural: true
    },
    {
        id: "C055",
        titulo: "Chamada Perdida",
        dificuldade: "FACIL",
        xp: 205,
        valorAdiantamento: 860,
        recompensa: 1000,
        tempoTotalHoras: 480,
        resumo: "Uma ligação decisiva em Atenas nunca chegou ao destinatário correto, embora conste como concluída. O atraso beneficiou alguém diretamente. Alguém interferiu no momento exato. Descubra quem manipulou a comunicação.",
        localInicial: { pais: "Grécia", cidade: "Atenas" },
        procedural: true
    },
    {
        id: "C056",
        titulo: "Lacre Intacto",
        dificuldade: "MEDIO",
        xp: 265,
        valorAdiantamento: 1200,
        recompensa: 2000,
        tempoTotalHoras: 384,
        resumo: "Uma remessa chegou a Casablanca com lacres aparentemente intactos, mas o conteúdo principal havia sumido. A substituição foi feita sem chamar atenção. O método usado indica experiência logística. Você deve encontrar onde a fraude ocorreu.",
        localInicial: { pais: "Marrocos", cidade: "Casablanca" },
        procedural: true
    },
    {
        id: "C057",
        titulo: "Mesa Vazia",
        dificuldade: "FACIL",
        xp: 210,
        valorAdiantamento: 900,
        recompensa: 1000,
        tempoTotalHoras: 480,
        resumo: "Ao amanhecer em Budapeste, uma mesa de trabalho foi encontrada vazia, sem documentos que deveriam estar ali. Nenhum acesso irregular foi registrado. O desaparecimento foi discreto e calculado. Sua missão é localizar quem limpou a cena.",
        localInicial: { pais: "Hungria", cidade: "Budapeste" },
        procedural: true
    },
    {
        id: "C058",
        titulo: "Passagem Duplicada",
        dificuldade: "MEDIO",
        xp: 270,
        valorAdiantamento: 1250,
        recompensa: 2000,
        tempoTotalHoras: 384,
        resumo: "Uma passagem internacional foi utilizada duas vezes em menos de uma hora em aeroportos diferentes. Os registros parecem autênticos e sincronizados. Há uma rede por trás da duplicação. Você precisa seguir a trilha e encontrar os envolvidos.",
        localInicial: { pais: "Nova Zelândia", cidade: "Auckland" },
        procedural: true
    },
    {
        id: "C059",
        titulo: "Caixa Lacrada",
        dificuldade: "FACIL",
        xp: 215,
        valorAdiantamento: 920,
        recompensa: 1000,
        tempoTotalHoras: 480,
        resumo: "Uma caixa lacrada desapareceu de um depósito em Oslo, embora ninguém tenha registrado sua retirada. O item não parecia importante para a maioria, mas alguém sabia seu valor real. Você deve localizar o autor do sumiço.",
        localInicial: { pais: "Noruega", cidade: "Oslo" },
        procedural: true
    },
    {
        id: "C060",
        titulo: "Registro Fantasma",
        dificuldade: "MEDIO",
        xp: 280,
        valorAdiantamento: 1300,
        recompensa: 2000,
        tempoTotalHoras: 384,
        resumo: "Um registro operacional apareceu em Singapura com autorização válida, mas ninguém reconhece a assinatura usada. O documento liberou processos importantes antes de sumir. O autor conhece bem os controles internos. Você deve encontrá-lo antes que use o método novamente.",
        localInicial: { pais: "Singapura", cidade: "Singapura" },
        procedural: true
    }
];

export const initialPlayer = {
    nome: "Recruta",
    nivel: 1,
    nivelTitulo: "Novato",
    classeEmoji: "🟢",
    classe: "Iniciante",
    xp: 0,
    dinheiro: 1000,
    especializacao: null,
    avatar: null,
    hardWins: 0,
    hardLosses: 0,
    legendaryWins: 0,
    legendaryLosses: 0,
    dailyStreak: 0,
    vouchers: [],
    settings: {
        musicEnabled: true,
        clickSoundEnabled: true
    }

};